version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $IMAGE_TAG
      - echo $IMAGE_REPO
      - docker build -f Dockerfile -t 'crypto-analysis:last' .
      - docker tag 'crypto-analysis:last' '....dkr.ecr.us-west-2.amazonaws.com/crypto-analysis:last'
  install:
    runtime-versions:
      docker: 18
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push '....dkr.ecr.us-west-2.amazonaws.com/crypto-analysis:last'
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)